### ISSUE TITLE
I'm a little confused. Is this project supposed to be working condition or is it still under development? Because I am getting a whole bunch of errors in the boiler project.

### ISSUE THREAD

**Issue by eliezerp3** [jakemcdermott/vue-django-rest-auth#5]

**Comment by jakemcdermott** [comment]
Hi @eliezerp3,

What errors are you seeing and what commands did you use to set things up?

**Comment by eliezerp3** [comment]
Went into 'client' folder and ran:
`yarn install`
`yarn run dev`
(Got a bunch of eslint errors here, so had to add '"linebreak-style": 0,' in the '.eslintrc.js' rules for windows and then it compiled fine)

Then went into the 'server' folder and ran
`pipenv install`
`pipenv shell`
`python manage.py migrate`
`python manage.py runserver`

When i go onto the django server (127....) I get this error:
![server](https://user-images.githubusercontent.com/30153503/54956041-4063e080-4f0c-11e9-81a7-ee944415242f.PNG)

And when I go onto the vuejs server (localhost), the login page comes up and the vue-router works but when i try to use the signup form to create a user, I get a 404 not found error:

![client](https://user-images.githubusercontent.com/30153503/54956157-8ae55d00-4f0c-11e9-8a2c-87bd5269fe5e.PNG)

Love what you made here. Thanks for the help.

**Comment by eliezerp3** [comment]
Just noticed that your ReadMe had more commands then the ones i did. So I added all of those also and it is still showing the same errors.

**Comment by jakemcdermott** [comment]
@eliezerp3 This may very well be a windows issue. That said, you might just need to run `yarn build`. This would put the `index.html` file in the expected location (`client\dist\index.html`).

I was able to generate a similar error on a mac by skipping `yarn build`.

**Comment by eliezerp3** [comment]
But then I would have to buld it again each and every time i wanted to use the api, no?

**Comment by jakemcdermott** [comment]
@eliezerp3 

It looks like you were trying navigate to the root of the django dev server (`127.0.0.1:8000`) in your browser. This will cause the dev server look for an `index.html` in `dist/index.html`, which only exists if you build the UI files.

This doesn't mean you need to build it to use the API, though. You should be able to browse the api by navigating to `127.0.0.1:8000/api` without building a UI.

**Comment by eliezerp3** [comment]
I meant that I would have to re-build it every time i made changes to my vue application but i guess i could use the vue server (localhost) and just send ajax requests to the django server and build it when its done. That should work.

**Comment by jakemcdermott** [comment]
Yep, that would work - After you're done working on the UI using the vuejs server (note that it has a different port than the django server: localhost:**8082**), you'd still need to build all of the UI files for real using `yarn build` once at the end. This is because the vuejs server is only building the UI files in memory, it never writes them to disk.

**Comment by eliezerp3** [comment]
So added a baseURL of 'http://127.0.0.1:8000' to the axios instance in api/session.js
Now the ajax requests get sent to the server, but since i'm using the vuejs server I'm having a problem with CORS policy. I turned on a cors extension on chrome and now the signup form works fine. Got the confirmation email in console, went to url and confirmation was successful.

But when I tried to log in, I keep getting 'DoesNotExist at /auth/login/' 500 error. I tried going to the page directly in the browser but i get the same message "DoesNotExist at /auth/login/". Went to /auth/ in browser and it shows that the urlmapping for /auth/login/ is there. But for some reason it says it doesn't exist when i try to access it.

**LIST OF URLMAPPING (as you can see /auth/login/ is there**

![list](https://user-images.githubusercontent.com/30153503/55035463-47a2f100-4fd5-11e9-9453-a4e778e449c4.PNG)

**LOCALHOST AJAX REQUEST**

![clientnew](https://user-images.githubusercontent.com/30153503/55035502-61dccf00-4fd5-11e9-8dc7-e5c0c6f96f97.PNG)

**DJANGO SERVER DIRECT**

![servernew](https://user-images.githubusercontent.com/30153503/55035543-76b96280-4fd5-11e9-8660-40f466f43b15.PNG)

Also just tried all of the other auth/* links and they also give same error. Also went on admin/ and typed in superuser password and then gives me same error that doesnt exist. I have no idea whats going on. It seems only registration/ link is working.

**Comment by eliezerp3** [comment]
I noticed the /registration link stopped working also with the same error. After playing around a little, I noticed that if I clear the cookies (csrf token) then it allows me back on again. But once I access any api page (registration, confirm email, admin) and get the cookie back then all pages stop working again. I have literally no idea why this is happening. I really want a vuejs drf authentication boiler plate project and this seems to be the only one so thank you very much for the help!

**Comment by jakemcdermott** [comment]
@eliezerp3 
You shouldn't need to add or change any base urls.

When you are using the vuejs server at `127.0.0.1:8082`, any request going to `127.0.0.1:8082/api/*` gets redirected to `127.0.0.1:8000/api/*` automatically via the webpack dev server proxy: https://github.com/jakemcdermott/vue-django-rest-auth/blob/master/client/config/index.js#L14.

**Comment by eliezerp3** [comment]
Its not opening the server at `127.0.0.1:8082` its opening in the regular default vuejs url `http://localhost:8080`. Tried going to that url and chrome has the standard `This site cannot be reached... Err connection refused` (the same page it shows for all non-existent domains.) 

If you tell me how to switch the dev default url, I'll see if that fixes the problem. But idk if thats really the issue since i tried `yarn run build` and using the regular server and having the same errors. Plus, i tried to access the login api directly via `http://127.0.0.1:8000/auth/login/` and it opened the default DRF page fine. But when i tried using the built-in form to post the username and password, I keep getting this page (its the same one as the ajax response sent the vuejs client when I try to login)

![qqqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/30153503/55157802-8f7f6080-511a-11e9-8153-fcd480bc0123.PNG)

**Comment by eliezerp3** [comment]
Ok. Finally figured out what was causing the problems. For some reason, the dev auth mode that is enabled by default `AUTHENTICATION_BACKENDS = ['server.auth.AlwaysRootBackend']` in settings was causing the errors for some reason. I commented that line out and now it works perfectly.

(1) Can you just let me know what that line was supposed to do? If it helps out alot for development then I might want to try to see if I can fix it or if I should just leave it off.
(2) Can you still please let me know how to run the vuejs server on `127.0.0.1:8082`. For some reason, I don't need CORS anymore. The ajax requests are working fine even though they are being posted to `localhost:8080/api..` but still might cause problems in the future.

I really appreciate it. Thank you very much for the help.
